version: '3'

services:
  # auth-postgres:
  #   image: 'postgres'
  #   container_name: 'auth-postgres'
  #   ports:
  #     - 5433
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - ./db_schema/user_management_service_init_db.sql:/docker-entrypoint-initdb.d/init.sql
  
  # auth-service:
  #   build: ./authservice
  #   container_name: 'auth-service'
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - DB_URL=jdbc:postgresql://auth-postgres/postgres?user=postgres&password=postgres
  #   depends_on:
  #     - auth-postgres
  # user-management-service:
  #   build: ./user-management-service
  #   container_name: 'user-management-service'
  #   ports:
  #     - 8082:8082
  #   environment:
  #     - DB_URL=jdbc:postgresql://auth-postgres/postgres?user=postgres&password=postgres
  #     - AUTH_SERVICE_URL=http://auth-service:8081/api/auth
  #   depends_on:
  #     - auth-postgres
  #     - auth-service
  
  checkerservice-postgres:
    image: 'postgres'
    restart: always
    container_name: 'checkerservice-postgres'
    ports:
      - 5434
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db_schema/checkerservice_postgres_init_db.sql:/docker-entrypoint-initdb.d/init.sql
  
  checkerservice:
    build: ./checkerservice
    restart: always
    container_name: 'checkerservice'
    ports:
      - 8084:8084
    environment:
      - DB_URL=jdbc:postgresql://checkerservice-postgres/postgres?user=postgres&password=postgres
      - AUTH_SERVICE_URL=http://auth-service:8081/api/auth
      - CHECKER_IMAGE_NAME=zaranik/checker:1.5.7
      - NETWORK_NAME=coursework_default
    depends_on:
      - checkerservice-postgres
#      - auth-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  solution-pipe-service:
    build: ./solution-pipe-service
    restart: always
    container_name: 'solution-pipe-service'
    ports:
      - 8085
    environment:
      - DB_URL=jdbc:postgresql://checkerservice-postgres/postgres?user=postgres&password=postgres
    depends_on:
      - checkerservice
      - checkerservice-postgres

  taskmanagement-service:
    build: ./taskmanagement-service
    restart: always
    container_name: 'taskmanagement-service'
    ports:
      - 8083:8083
    environment:
      - DB_URL=jdbc:postgresql://checkerservice-postgres/postgres?user=postgres&password=postgres
    depends_on:
      - checkerservice-postgres