server:
  port: 8084

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb?user=postgres&password=zaranik
  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB

auth-service:
  url: someUrlHere

container:
  docker:
    start-command: "docker run -e SOLUTION_ID=%d zaranik/checker:1.5.7"
