server:
  port: 8084

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB

auth-service:
  url: ${AUTH_SERVICE_URL}

container:
  docker:
    start-command: "docker run --network=coursework_default -e SOLUTION_ID=%d --privileged -v /var/run/docker.sock:/var/run/docker.sock ${CHECKER_IMAGE_NAME}"
