server:
  port: 8082
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate

auth-service:
  url: ${AUTH_SERVICE_URL}

springdoc:
  swagger-ui:
    path: /swagger

ratelimit:
  bucketCapacity: ${RATE_LIMIT_BUCKET_CAPACITY}
  durationInMinutes: ${RATE_LIMIT_DURATION_IN_MINUTES}