server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate

zaranik:
  app:
    jwtAccessTokenExpirationSeconds: 900 # 15 minutes
    jwtRefreshTokenExpirationSeconds: 2678400 # a one month
    jwtSecret: BogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranik
springdoc:
  swagger-ui:
    path: /swagger