server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: "sa"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update

zaranik:
  app:
    jwtAccessTokenExpirationSeconds: 900 # 15 minutes
    jwtRefreshTokenExpirationSeconds: 2678400 # a one month
    jwtSecret: BogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranik
springdoc:
  swagger-ui:
    path: /swagger


