server:
  port: 8082
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${DB_HOST}/postgres
  jpa:
    hibernate:
      ddl-auto: validate

auth-service:
  url: http://${AUTH_SERVICE_HOST}/api/auth
zaranik:
  app:
    jwtSecret: BogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranik

springdoc:
  swagger-ui:
    path: /swagger