server:
  port: 7001
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: zaranik
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

auth-service:
  url: http://localhost:8081/api/auth

springdoc:
  swagger-ui:
    path: /swagger

ratelimit:
  bucketCapacity: 1
  durationInMinutes: 1