server:
  port: 8082
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate

auth-service:
  url: ${AUTH_SERVICE_URL}
zaranik:
  app:
    jwtSecret: BogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranikBogdanZaranik

springdoc:
  swagger-ui:
    path: /swagger