name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      auth-service-working-directory: ./authservice
      checker-service-working-directory: ./checkerservice
      solution-pipe-service-working-directory: ./solution-pipe-service
      task-management-service-working-directory: ./taskmanagement-service
      user-management-service-working-directory: ./user-management-service
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build and analyze solution pipe service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
              mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GeniusDP_coursework sonar:sonar -Pcoverage
        working-directory: ${{env.solution-pipe-service-working-directory}}

      - name: Build and analyze auth service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
              mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GeniusDP_coursework sonar:sonar -Pcoverage
        working-directory: ${{env.auth-service-working-directory}}
      
      - name: Build and analyze checker service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
              mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GeniusDP_coursework sonar:sonar -Pcoverage
        working-directory: ${{env.checker-service-working-directory}}
      

      - name: Build and analyze task management service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
              mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GeniusDP_coursework sonar:sonar -Pcoverage
        working-directory: ${{env.task-management-service-working-directory}}

      - name: Build and analyze user management service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
              mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GeniusDP_coursework sonar:sonar -Pcoverage
        working-directory: ${{env.user-management-service-working-directory}}
